# Generated by Django 3.0.6 on 2020-05-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=100)),
                ('total_quantity', models.SmallIntegerField(default=1)),
                ('added_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('vendor_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity_left', models.SmallIntegerField(default=1)),
                ('prod_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eCartApp.Product')),
                ('vendor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_to_sell', to='eCartApp.Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sold_by',
            field=models.ManyToManyField(blank=True, related_name='products', to='eCartApp.Vendor'),
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_wanted', models.SmallIntegerField(default=1)),
                ('cart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_in_cart', to='eCartApp.Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCartApp.VendorProduct')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_cart', to='eCartApp.Customer'),
        ),
        migrations.AddConstraint(
            model_name='vendorproduct',
            constraint=models.UniqueConstraint(fields=('prod_id', 'vendor_id'), name='unique_prod_vendor_pair'),
        ),
        migrations.AddConstraint(
            model_name='cartproduct',
            constraint=models.UniqueConstraint(fields=('product', 'cart'), name='unique_prod_cart_pair'),
        ),
    ]
